# Site settings
title: Eric Liu Blog
SEOTitle: 刘威博客 | Eric Liu Blog
header-img: img/home-bg.jpg
email: hokkyliu@gmail.com
description: "电子与设计、剑与诗 | 刘威，Web & Mobile Lover，Python，Linux | 这里是 @hokkyliu 的个人博客，与你一起发现更大的世界。"
keyword: "刘威, hokkyliu刘威, hokkyliu, @hokkyliu, 刘威的博客, Eric Liu Blog, 博客, 个人网站, 互联网, 电子, 设计, 产品"
url: "http://www.liuway.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     hokkyliu
zhihu_username:     liu-wei-59-10-39
github_username:    accbest
#twitter_username:  hokkyliu
#facebook_username:  hokkyliu
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: Ericblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: liuway.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Su",
        href: "http://su.gallery/"
    },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]


# Defines all Languages known to GitHub.
  #
  # type              - Either data, programming, markup, prose, or nil
  # aliases           - An Array of additional aliases (implicitly
  #                     includes the lowercase name with spaces replaced
  #                     by dashes)
  # ace_mode          - A String name of the Ace Mode used for highlighting whenever
  #                     a file is edited. This must match one of the filenames in http://git.io/3XO_Cg.
  #                     Use "text" if a mode does not exist.
  # codemirror_mode   - A String name of the CodeMirror Mode used for highlighting whenever a file is edited.
  #                     This must match a mode from https://git.io/vi9Fx
  # wrap              - Boolean wrap to enable line wrapping (default: false)
  # extensions        - An Array of associated extensions (the first one is
  #                     considered the primary extension, the others should be
  #                     listed alphabetically)
  # interpreters      - An Array of associated interpreters
  # searchable        - Boolean flag to enable searching (defaults to true)
  # language_id       - Integer used as a language-name-independent indexed field so that we can rename
  #                     languages in Linguist without reindexing all the code on GitHub. Must not be
  #                     changed for existing languages without the explicit permission of GitHub staff.
  # color             - CSS hex color to represent the language. Only used if type is "programming" or "prose".
  # tm_scope          - The TextMate scope that represents this programming
  #                     language. This should match one of the scopes listed in
  #                     the grammars.yml file. Use "none" if there is no grammar
  #                     for this language.
  # group             - Name of the parent language. Languages in a group are counted
  #                     in the statistics as the parent language.
  #
  # Any additions or modifications (even trivial) should have corresponding
  # test changes in `test/test_blob.rb`.
  #
  # Please keep this list alphabetized. Capitalization comes before lowercase.